feat: add run script to check if executable is installed globally

diff --git a/.github/workflows/install.yml b/.github/workflows/install.yml
--- a/.github/workflows/install.yml
+++ b/.github/workflows/install.yml
@@ -11,10 +11,18 @@ jobs:
           chmod +x scripts/install.sh
           ./scripts/install.sh
       - run: |
-          if command -v deno; then
+          if command -v deno &>/dev/null; then
             echo "Deno is installed."
             deno --version
           else
             echo "Deno installation failed."
+            exit 1
+          fi
+      - run: |
+          if command -v cocli &>/dev/null; then
+            echo "Cocli is installed globally."
+            cocli --version
+          else
+            echo "Cocli installation globally failed."
             exit 1
           fi
